{"uuid":"1a3e478d-844e-4210-964f-34c9c873bac4","historyId":"86892090166995669cbc5816bbf6cedb","fullName":"tests.sauceDemo.LoginTest.loginLockedUser","labels":[{"name":"package","value":"tests.sauceDemo.LoginTest"},{"name":"testClass","value":"tests.sauceDemo.LoginTest"},{"name":"testMethod","value":"loginLockedUser"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"TestNGTest-61be11fd-7f1b-4b9d-8f60-131d7112bb64"},{"name":"subSuite","value":"tests.sauceDemo.LoginTest"},{"name":"host","value":"DESKTOP-PF8F9B0"},{"name":"thread","value":"3588@DESKTOP-PF8F9B0.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"loginLockedUser","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"El mensaje esperado no es el correcto, se visualiza el siguiente mensaje: Epic sadface: Sorry, this user has been locked out. expected [Epic sadface: Sorry, this user has been locked outa.] but found [Epic sadface: Sorry, this user has been locked out.]","trace":"java.lang.AssertionError: El mensaje esperado no es el correcto, se visualiza el siguiente mensaje: Epic sadface: Sorry, this user has been locked out. expected [Epic sadface: Sorry, this user has been locked outa.] but found [Epic sadface: Sorry, this user has been locked out.]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:656)\r\n\tat tests.sauceDemo.LoginTest.loginLockedUser(LoginTest.java:31)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.microsoft.java.test.runner.testng.TestNGRunner.run(TestNGRunner.java:45)\r\n\tat com.microsoft.java.test.runner.testng.TestNGLauncher.execute(TestNGLauncher.java:32)\r\n\tat com.microsoft.java.test.runner.Launcher.main(Launcher.java:57)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1734442142451,"stop":1734442143135}